import { chromium } from 'playwright-core';
const [base, out, path] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 412, height: 915 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.type()+': '+m.text()); });
await page.goto(base + path);
await page.waitForFunction(() => window.proto?.shell, null, { timeout: 90000 });
await page.waitForTimeout(5000);
console.log(await page.evaluate(() => JSON.stringify({ v: window.proto.view, cw: document.querySelector('#c').clientWidth, ch: document.querySelector('#c').clientHeight, segs: window.proto.net.segs.size, b: window.proto.buildings.length })));
await page.screenshot({ path: out + '/dbg.png' });
console.log('errors', JSON.stringify(errs));
await browser.close();
